### ISSUE TITLE
Facilitando o PIX (ainda mais)

### ISSUE THREAD

**Issue by renie** [bivardourado/Seu_Time#2]
Que tal adicionar o QR Code do PIX logo abaixo do número? Existem formas programática de fazer isso, mas num primeiro momento poderia ser uma imagem simples mesmo.
Uma segunda sugestão seria gerar no seu banco uma chave aleatória de PIX, dessa forma o senhor não precisa deixar o seu telefone tão público.

**Comment by bivardourado** [comment]
Obrigado!
